version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: express-app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app       # Synchronisation en temps réel
      - /app/node_modules     # Pour éviter que node_modules soit écrasé
    environment:
      - MONGO_URL=mongodb://admin:secret@mongodb:27017
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react-app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "3000:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - app_net

volumes:
  mongo-data:
networks:
  app_net:
